Feature Selection

In [2]:
# Importing the libraries
import numpy as np
import pandas as pd

In [3]:
# Importing the dataset

dataset = pd.read_csv('data-1.csv')
dataset

offer  Age  online payment  items
0      1   35               0      5
1      1   26               0      4
2      1   41               0      9
3      1   34               0     10
4      1   38               0      3

Dropping features with Zero Variance

In [4]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold = 0.0)
selector.fit_transform(dataset)

array([[35,  5],
       [26,  4],
       [41,  9],
       [34, 10],
       [38,  3]], dtype=int64)

Dropping features with Low variance (less than threshold)

In [6]:
# Importing the dataset

dataset = pd.read_csv('data-2.csv')
dataset

referred  repeat  Age  Promoted  items
0         1       0   35         1      5
1         0       0   26         0      4
2         1       0   41         1      9
3         1       1   34         0     10
4         1       0   38         1      3
5         1       0   40         0      7

In [7]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold = 0.16)
selector.fit_transform(dataset)

array([[35,  1,  5],
       [26,  0,  4],
       [41,  1,  9],
       [34,  0, 10],
       [38,  1,  3],
       [40,  0,  7]], dtype=int64)

Univariate Feature Selection

In [8]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.datasets import load_iris

In [9]:
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

In [12]:
#Select 3 best features

X_select = SelectKBest(chi2, k=3).fit_transform(X, y)
X_select.shape

(150, 3)

In [13]:
X_select

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.2],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.4, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

Model Based Feature Selection

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectFromModel
iris = load_iris()
X,y = iris.data, iris.target
X.shape

(150, 4)

In [17]:
clf = RandomForestClassifier(n_estimators =10)
clf = clf.fit(X,y)
clf.feature_importances_

array([0.21975678, 0.03171062, 0.45138561, 0.29714698])

model = SelectorFromModel(clf, Prefit =True) 

In [ ]:
model = SelectFromModel(clf, prefit = True)
X_new = model.transform(X)
X_new.shape

Feature Selection using pipeline

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
clfs = Pipeline([
    ('feature_selection', SelectFromModel(RandomForestClassifier(n_estimators = 10))),
    ('classification',KNeighborsClassifier())
])
model = clfs.fit(X,y)